# Generated by Django 4.1 on 2024-08-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_tool", "0002_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gene",
            table="Gene",
        ),
    ]
