# Generated by Django 4.1 on 2024-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_tool", "0003_alter_gene_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="W293",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wormbase_id", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("sequence_name", models.TextField(blank=True, null=True)),
                ("other_name", models.TextField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "W293",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="WebToolGene",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
