# Generated by Django 4.1 on 2024-09-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_tool", "0004_w293_delete_webtoolgene_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="web_tool_user",
        ),
    ]
